### ISSUE TITLE
Create empty folders

### ISSUE THREAD

**Issue by maQus123** [aloneguid/storage#114]
With `IBlogStorage.WriteAsync()` I can upload a new file in a new folder. But what if I just want to create a new folder without any files in it?

**Comment by aloneguid** [comment]
This is not possible at the moment, because most cloud storage providers do not support folders. The questions is mostly around designing this - what to expect (from a method call) when folders are not supported?

**Comment by maQus123** [comment]
I see. As a hack, isn't it just like creating a 0KB file in a new folder and removing it right after so that just the new folder remains? But that would be a dirty hack anyway. I'm only used to Azure Blob Storage and local storage, both support folders as far as I know. I think Azure just doesn't call it folder but container. What about returning a `StorageOperationNotSupportedException` promting that the operation to create a new folder is not supported on that particular storage?

**Comment by aloneguid** [comment]
Azure Blob storage doesn't support folders actually. Storage explorer renders them based on presence of / in the filename. Let me think about it, will come back soon.

**Comment by aloneguid** [comment]
There is an extension method on [IBlobStorage](https://github.com/aloneguid/storage/blob/635b573b0dea0ebc7cb2536d6b6c8bc424262435/src/Storage.Net/Blobs/BlobStorageExtensions.cs#L421) that "sort of" creates a folder. Although some (most) implementations don't support folders, this method will create a dummy file on the path so that the virtual folder appears in list results. If an implementation actually supports folders, it will try to use the native API to do so. This method is used in StorAmp desktop utility to create folders visually

<a href='//www.microsoft.com/store/apps/9NKV1D43NLL3?cid=storebadge&ocid=badge'>
   <img src='https://assets.windowsphone.com/85864462-9c82-451e-9355-a3d5f874397a/English_get-it-from-MS_InvariantCulture_Default.png' alt='English badge' style='width: 284px; height: 104px;' width='284' height='104'/>
</a>

Note that not all of the providers that support folders are actually fully utilised, so you may still see dummy files in something like ADLS Gen1, because I simply didn't have time to implement it.

**Comment by aloneguid** [comment]
closing as this is supported now
