### ISSUE TITLE
Move interfaces to Storage.Net.Abstractions

### ISSUE THREAD

**Issue by RicoSuter** [aloneguid/storage#85]
Thanks for this library, I think it makes a lot sense to abstract this stuff... I planned to do something similar but then found this library. 

Wouldn't it be a good idea to move all interfaces (which should be super stable) to an own package which is called e.g. Storage.Net.Abstraction (like [Microsoft.Extensions.Logging.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions)) which will be super stable without any external NuGet dependencies. 

This way "service" libraries only need to reference this super thin abstraction library and only the app roots (where you set up the DI system, etc.) needs to reference the actual implementations. This way you it's easier to avoid versioning problems (as most libs only depend on this abstactions lib) and the libs only reference a single abstaction lib.

**Comment by aloneguid** [comment]
Yes, it makes sense, however primary library doesn't have any dependencies, i'm very careful about this. Anything extra goes to a separate package.

**Comment by RicoSuter** [comment]
It references NetBox which is not needed for the interfaces (I think) and also it exports public apis which are not needed only for the abstractions... also it would avoid versioning issues in larger projects when Storage.Net.Abstractions is versioned independently (i.e. extremely stable at v1.0.0 for a long time) whereas the main package Storage.Net can be moved forward independently as it is then only used in the app root which is not shared between projects and thus should not give versioning issues (diamond dependency problem).

**Comment by jussimattila** [comment]
This library looks really great! I'm currently "test-driving" it, looking to replace an in-house file/blob storage abstraction for our next project.

Since NetBox was mentioned, I'd like to say that getting that dependency with Storage.Net was something I didn't particularly like. I don't mind the extra dependency per se, but adding Strorage.Net to the project causes Intellisense to start listing NetBox's extension methods for basic framework classes (string, DateTime, int, IEnumerable, Type, Stream, etc.). Admittedly, this is not a big problem, but I still find it a bit annoying that the most common classes, which are being used everywhere, now list quite a few "unwanted" extension methods when I'm developing.

I don't have great a suggestion how to change this. One option would be to have a base NetBox library that provides the method implementations, but not the extension methods to the common classes. Then you'd have another NuGet, NetBox.Extensions, which would provide the extension methods. Storage.Net could then rely on the non-extension NuGet. Or maybe the other way around, to not break current clients. That is, move implentation to NetBox.Implementation and leave extensions in NetBox.

Sorry to have the first comment sound so negative. My feelings towards Storage.Net are actually very positive. In fact, after looking at several blob storage abstraction libraries, I think this one hits the sweet spot for our use case! :)

**Comment by RicoSuter** [comment]
My proposal would be this: 
https://github.com/aloneguid/storage/pull/89

For me it still contains a bit too much implementation (just copied the interfaces & the needed.
The abstractions project: 
https://github.com/RicoSuter/storage/tree/features/move-to-abstractions-package/src/Storage.Net.Abstractions

**Comment by aloneguid** [comment]
@jussimattila I understand, thanks for the feedback. Netbox puts all of the extension methods in a separate namespace "Netbox.Extensions" meanings that you shouldn't see them in you code's intellisense unless specifically referencing this namespace. This was done a while ago, unless there is a bug?

**Comment by aloneguid** [comment]
@RicoSuter base library is around 80k, really small. Also implementations are private library members, therefore it's impossible to make a dependency on them. Currently If interfaces change, the library increments major version to indicate a breaking change. I think "abstractions" package would work if it had a separate lifecycle i.e. dedicated CI/CD pipeline, repository etc. but this is not how things are built at the moment. It would require more work and more contributors to support it. Even if we did have resources, you'd still have to reference at least two libraries - abstractions and base library, and it just becomes a more complicated dependency graph that needs extra care and more development hours.

**Comment by jussimattila** [comment]
@aloneguid I'm using VS 2019. Not sure if it is a new feature, but Intellisense now discovers all extension methods, even those that have not been imported. Picking one from the list adds the `using` directive to the file automatically, as you'd expect. We can definitely live with this, but I think it is also good for you to be aware about this.

**Comment by aloneguid** [comment]
Interesting. Do you use any third-party plugins i.e. Resharper?

**Comment by jussimattila** [comment]
Yes, I do have ReSharper installed.

**Comment by aloneguid** [comment]
This might be Resharper's feature, as I don't see it happening in VS 2019.

**Comment by jussimattila** [comment]
I think it might be the new [VS IntelliCode](https://visualstudio.microsoft.com/services/intellicode/), which I have enabled in the test project.

**Comment by aloneguid** [comment]
Hm I understand no one wants to see extension methods even if it's a tooling issue. I'm not sure what's the best way to remove those. 

One option is to copy-paste code that is used into storage.net, but that's dirty and goes out of hand quick.

Another one is reference it as a git module and compile as private code, and I think i'd prefer it to the first option.

Anything else?

**Comment by jussimattila** [comment]
I just now realized that actually lots of methods from all included libraries are listed, but I haven't paid much attention to this before. I explicitly imported all those NuGets in the project and was not surprised when IntelliCode offered them for use. But, after adding Storage.Net, I was seeing things in the list that I didn't recognize. They also resolved to a previously unknown namespace NetBox. In this case, it might actually help if the namespace was just NetBox (or StorageNet), because then IntelliCode would show `using NetBox` (or `using StorageNet`). See the screenshot for reference. Of course, after adding Storage.Net users would still be required to make the connection (NetBox dependency) on their own.

![image](https://user-images.githubusercontent.com/8625258/60714761-5b3eeb80-9f24-11e9-821c-de3ded4603f3.png)

I guess the only way to change this behavior is to not have those extensions publicly available in the NuGets that Storage.Net adds. But please don't prioritize this because of me. :) Like I said, we can live with things the way they are.

**Comment by RicoSuter** [comment]
These extension methods are in the "Extensions.*" namespace?

**Comment by jussimattila** [comment]
Correct, NetBox extension methods are in a separate namespace "Netbox.Extensions".

**Comment by aloneguid** [comment]
Probably not going to happen any time soon - I'm not keen to copy-paste utility methods as they won't be supported anymore.

**Comment by fubar-coder** [comment]
Not having a direct dependency on NetBox would be nice. The current library layout includes this reference in all packages that might just need the interfaces.

**Comment by RicoSuter** [comment]
I’ve decided to write my own lib where so that im able to manage some features which are important to me (https://github.com/RicoSuter/Namotion.Messaging)

**Comment by aloneguid** [comment]
Good luck, this is a long and hard journey )

**Comment by aloneguid** [comment]
@RicoSuter would you mind creating this repository as a fork, as it's clearly a copy from this repo and we need to be visible even under terms of the MIT license. Thanks.

**Comment by RicoSuter** [comment]
Its not a fork no.. where do you see copied code?
